name: portfolio_website
description: "A new Flutter project."
publish_to: 'none' 

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dartz: ^0.10.1
  google_fonts: ^6.3.1
  url_launcher: ^6.3.2
  flutter_animate: ^4.5.2
  simple_animations: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/images/